[build]
	functions = "functions"
	publish = "dist"

[functions]
	node_bundler = "esbuild"

[[headers]]
	for = "/manifest.webmanifest"
	[headers.values]
		Content-Type = "application/manifest+json"

[dev]
	targetPort = 5173
